version: '3.8'

networks:
  app-network:
    driver: overlay
    internal: true  
  test-app_default: 
    external: true

volumes:
  mongo-data:

secrets:
  jwt_secret:
    external: true

services:
  planit-frontend:
    image: edwardkemp/planit-frontend:latest
    networks:
      - test-app_default
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Router for Non-WWW Domain
        - "traefik.http.routers.planit-frontend.rule=Host(`planit.edward-codes.com`)"
        - "traefik.http.routers.planit-frontend.entrypoints=websecure"
        - "traefik.http.routers.planit-frontend.tls.certresolver=le"
        - "traefik.http.services.planit-frontend.loadbalancer.server.port=5173"

    environment:
      VITE_API_URL: "https://planit.edward-codes.com/api"

  planit-backend:
    image: edwardkemp/planit-backend:latest
    networks:
      - test-app_default
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Router for Backend API
        - "traefik.http.routers.planit-backend.rule=Host(`planit.edward-codes.com`) && PathPrefix(`/api`)"
        - "traefik.http.routers.planit-backend.entrypoints=websecure"
        - "traefik.http.routers.planit-backend.tls.certresolver=le"
        - "traefik.http.services.planit-backend.loadbalancer.server.port=4000"

    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: eisenhower_prod
    secrets:
      - jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - app-network  # Only internal communication
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_DATABASE: eisenhower_prod
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: overlay
    internal: true
  test-app_default:
    external: true
