version: '3.8'

networks:
  app-network:
    driver: overlay

volumes:
  mongo-data:

secrets:
  jwt_secret:
    external: true
  mongo_root_user:
    external: true
  mongo_root_password:
    external: true

services:
  traefik-sub:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=app-network"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.le.acme.email=edwardlanekemp@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme-planit.json"
      - "--certificatesresolvers.le.acme.tlsChallenge=true"
      - "--api.insecure=false"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme-planit.json:/acme-planit.json"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  planit-frontend:
    image: edwardkemp/planit-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.planit-frontend.rule=Host(`planit.edward-codes.com`)"
      - "traefik.http.routers.planit-frontend.entrypoints=websecure"
      - "traefik.http.routers.planit-frontend.tls.certresolver=le"
      - "traefik.http.services.planit-frontend.loadbalancer.server.port=5173"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VITE_API_URL: "https://planit.edward-codes.com/api"

  planit-backend:
    image: edwardkemp/planit-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.planit-backend.rule=Host(`planit.edward-codes.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.planit-backend.entrypoints=websecure"
      - "traefik.http.routers.planit-backend.tls.certresolver=le"
      - "traefik.http.services.planit-backend.loadbalancer.server.port=4000"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
      MONGO_ROOT_USER: /run/secrets/mongo_root_user
      MONGO_ROOT_PASSWORD: /run/secrets/mongo_root_password
    secrets:
      - jwt_secret
      - mongo_root_user
      - mongo_root_password

  mongo:
    image: mongo:latest
    container_name: planit-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - mongo_root_user
      - mongo_root_password
    environment:
      MONGO_INITDB_DATABASE: eisenhower_prod
    entrypoint: >
      bash -c "export MONGO_INITDB_ROOT_USERNAME=$(cat /run/secrets/mongo_root_user) &&
               export MONGO_INITDB_ROOT_PASSWORD=$(cat /run/secrets/mongo_root_password) &&
               exec docker-entrypoint.sh"

