version: '3.8'

networks:
  test-app_default:
    external: true

secrets:
  jwt_secret:
    external: true
  cf_api_key:
    external: true

services:
  planit-frontend:
    image: edwardkemp/planit-frontend:latest
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Router for Non-WWW Domain
        - "traefik.http.routers.planit-frontend.rule=Host(`planit.edward-codes.com`)"
        - "traefik.http.routers.planit-frontend.entrypoints=websecure"
        - "traefik.http.routers.planit-frontend.tls.certresolver=le"
        - "traefik.http.services.planit-frontend.loadbalancer.server.port=5173"

        # Middleware for Redirecting WWW to Non-WWW
        - "traefik.http.middlewares.redirect-www-planit.redirectregex.regex=^https?://www\\.planit\\.edward-codes\\.com/(.*)"
        - "traefik.http.middlewares.redirect-www-planit.redirectregex.replacement=https://planit.edward-codes.com/$${1}"
        - "traefik.http.middlewares.redirect-www-planit.redirectregex.permanent=true"

        # Router for WWW Domain
        - "traefik.http.routers.redirect-www-planit.rule=Host(`www.planit.edward-codes.com`)"
        - "traefik.http.routers.redirect-www-planit.entrypoints=websecure"
        - "traefik.http.routers.redirect-www-planit.middlewares=redirect-www-planit"
        - "traefik.http.routers.redirect-www-planit.tls.certresolver=le"
        - "traefik.http.routers.redirect-www-planit.service=planit-frontend"

    environment:
      VITE_NODE_ENV: production
      VITE_API_URL: "https://planit.edward-codes.com/api"

  planit-backend:
    image: edwardkemp/planit-backend:latest
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Router for Backend API
        - "traefik.http.routers.planit-backend.rule=Host(`planit.edward-codes.com`) && PathPrefix(`/api`)"
        - "traefik.http.routers.planit-backend.entrypoints=websecure"
        - "traefik.http.routers.planit-backend.tls.certresolver=le"
        - "traefik.http.services.planit-backend.loadbalancer.server.port=4000"

    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: eisenhower_prod
    secrets:
      - jwt_secret

  mongo:
    image: mongo:latest
    networks:
      - test-app_default
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_DATABASE: eisenhower_prod

volumes:
  mongo-data:
