version: '3.8'

networks:
  test-app_default:
    external: true

secrets:
  jwt_secret:
    external: true
  cf_api_key:
    external: true

services:
  planit-frontend:
    image: edwardkemp/planit-frontend:latest
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Base service configuration
        - "traefik.http.services.planit-frontend.loadbalancer.server.port=5173"
        
        # Non-WWW Router
        - "traefik.http.routers.planit-frontend.rule=Host(`planit.edward-codes.com`)"
        - "traefik.http.routers.planit-frontend.entrypoints=websecure"
        - "traefik.http.routers.planit-frontend.tls.certresolver=le"
        - "traefik.http.routers.planit-frontend.service=planit-frontend"
        
        # WWW Router
        - "traefik.http.routers.planit-frontend-www.rule=Host(`www.planit.edward-codes.com`)"
        - "traefik.http.routers.planit-frontend-www.entrypoints=websecure"
        - "traefik.http.routers.planit-frontend-www.tls.certresolver=le"
        - "traefik.http.routers.planit-frontend-www.middlewares=redirect-to-non-www"
        
        # HTTP to HTTPS redirect
        - "traefik.http.routers.planit-frontend-http.rule=Host(`planit.edward-codes.com`) || Host(`www.planit.edward-codes.com`)"
        - "traefik.http.routers.planit-frontend-http.entrypoints=web"
        - "traefik.http.routers.planit-frontend-http.middlewares=redirect-to-https"
        
        # Middlewares
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https://www\\.planit\\.edward-codes\\.com/(.*)"
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://planit.edward-codes.com/$${1}"
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"
        
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

    environment:
      VITE_NODE_ENV: production
      VITE_API_URL: "https://planit.edward-codes.com/api"

  planit-backend:
    image: edwardkemp/planit-backend:latest
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.planit-backend.rule=Host(`planit.edward-codes.com`) && PathPrefix(`/api`)"
        - "traefik.http.routers.planit-backend.entrypoints=websecure"
        - "traefik.http.routers.planit-backend.tls.certresolver=le"
        - "traefik.http.services.planit-backend.loadbalancer.server.port=4000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: eisenhower_prod
    secrets:
      - jwt_secret

  mongo:
    image: mongo:latest
    networks:
      - test-app_default
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_DATABASE: eisenhower_prod

volumes:
  mongo-data:
