networks:
  app-network:
    driver: overlay 

volumes:
  mongo-data:

secrets:
  jwt_secret:
    file: /run/secrets/jwt_secret
  mongo_uri:
    file: /run/secrets/mongo_uri

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.le.acme.email=edwardlanekemp@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlsChallenge=true"
      - "--api.insecure=false" # Disable Traefik dashboard in production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: edwardkemp/frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`planit.edward-codes.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      VITE_API_URL: "https://planit.edward-codes.com/api"

  backend:
    image: edwardkemp/backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`planit.edward-codes.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: production
    secrets:
      - jwt_secret
      - mongo_uri

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
