name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push planit-frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/planit-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/planit-frontend:${{ github.sha }}

      - name: Build and push planit-backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/planit-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/planit-backend:${{ github.sha }}

      - name: Add Host Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail
            IFS=$'\n\t'

            # Variables
            PROJECT_DIR="/home/edwardkemp/websites/eisenhower-matrix-app"
            REPO_URL="git@github.com:Steadyx/eisenhower-matrix.git"
            BRANCH="main"

            # Navigate to project directory
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project directory does not exist. Cloning repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
            else
              echo "Project directory exists. Pulling latest changes..."
              cd "$PROJECT_DIR"

              echo "Fetching latest changes..."
              git fetch origin

              echo "Resetting local changes..."
              git reset --hard origin/"$BRANCH"
            fi

            # Ensure acme-planit.json exists with correct permissions
            ACME_FILE="$PROJECT_DIR/acme-planit.json"
            if [ ! -f "$ACME_FILE" ]; then
              echo "Creating acme-planit.json file for Let's Encrypt."
              sudo touch "$ACME_FILE"
            fi
            sudo chmod 600 "$ACME_FILE"

            # Pull latest Docker images
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/planit-frontend:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/planit-backend:latest

            # Stop existing Docker stack
            if sudo docker stack ls | grep -q eisenhower-matrix-app; then
              echo "Stopping existing Docker stack..."
              sudo docker stack rm eisenhower-matrix-app

              echo "Waiting for stack removal..."
              while sudo docker stack ls | grep -q eisenhower-matrix-app; do
                echo "Waiting for stack to be removed..."
                sleep 5
              done
            else
              echo "Stack eisenhower-matrix-app does not exist."
            fi

            # Prune Docker system
            echo "Pruning Docker system to remove unused data..."
            sudo docker system prune -f --volumes

            # Remove and recreate Docker secrets
            recreate_secret() {
              local secret_name="$1"
              local secret_value="$2"

              if sudo docker secret ls --format '{{.Name}}' | grep -q "^$secret_name$"; then
                echo "Removing existing secret: $secret_name"
                sudo docker secret rm "$secret_name"
              fi

              echo "Creating secret: $secret_name"
              echo "$secret_value" | sudo docker secret create "$secret_name" -
            }

            recreate_secret jwt_secret "${{ secrets.JWT_SECRET }}"

            # Deploy updated stack with retries
            retry_count=0
            max_retries=3
            while true; do
              if sudo docker stack deploy -c "$PROJECT_DIR/docker-compose.prod.yml" eisenhower-matrix-app; then
                echo "Deployment completed successfully."
                break
              fi

              retry_count=$((retry_count+1))
              if [ $retry_count -ge $max_retries ]; then
                echo "Failed to deploy stack after $max_retries attempts."
                exit 1
              fi

              echo "Retrying stack deployment... Attempt $retry_count"
              sleep 5
            done
