name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push planit-frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/planit-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/planit-frontend:${{ github.sha }}

      - name: Build and push planit-backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/planit-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/planit-backend:${{ github.sha }}

      - name: Add Host Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail
            IFS=$'\n\t'

            # Variables
            PROJECT_DIR="/home/edwardkemp/websites/eisenhower-matrix-app"
            REPO_URL="git@github.com:Steadyx/eisenhower-matrix.git"
            BRANCH="main"

            echo "Navigating to project directory..."
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project directory does not exist. Cloning repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
            else
              echo "Project directory exists. Pulling latest changes..."
              cd "$PROJECT_DIR"

              echo "Fetching latest changes..."
              git fetch origin

              echo "Resetting local changes..."
              git reset --hard origin/"$BRANCH"
            fi

            echo "Ensuring acme-planit.json exists with correct permissions..."
            ACME_FILE="$PROJECT_DIR/acme-planit.json"
            if [ ! -f "$ACME_FILE" ]; then
              echo "Creating acme.json file for Let's Encrypt."
              sudo touch "$ACME_FILE"
            fi
            sudo chmod 600 "$ACME_FILE"

            echo "Pulling latest Docker images..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/planit-frontend:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/planit-backend:latest

            echo "Stopping existing Docker stack..."
            sudo docker stack rm eisenhower-matrix-app || echo "Stack eisenhower-matrix-app does not exist."

            echo "Waiting for stack and network removal..."
            while sudo docker stack ls | grep -q eisenhower-matrix-app || sudo docker network ls | grep -q eisenhower-matrix-app_app-network; do
              echo "Waiting for stack or network to be removed..."
              sleep 5
            done

            if ! sudo docker network ls | grep -q eisenhower-matrix-app_app-network; then
              echo "Creating overlay network..."
              sudo docker network create --driver overlay eisenhower-matrix-app_app-network
            else
              echo "Overlay network already exists."
            fi

            echo "Pruning Docker system to remove unused data..."
            sudo docker system prune -f --volumes

            echo "Removing and recreating Docker secrets..."
            recreate_secret() {
              local secret_name="$1"
              local secret_value="$2"

              if sudo docker secret ls --format '{{.Name}}' | grep -q "^$secret_name$"; then
                echo "Removing existing secret: $secret_name"
                sudo docker secret rm "$secret_name"
              fi

              echo "Creating secret: $secret_name"
              echo "$secret_value" | sudo docker secret create "$secret_name" -
            }

            recreate_secret jwt_secret "${{ secrets.JWT_SECRET }}"
            recreate_secret cf_api_key "${{ secrets.CF_API_KEY }}"
            recreate_secret cf_api_email "${{ secrets.CF_API_EMAIL }}"

            echo "Deploying the updated stack..."
            retry_count=0
            max_retries=3
            until sudo docker stack deploy -c /home/edwardkemp/websites/eisenhower-matrix-app/docker-compose.prod.yml eisenhower-matrix-app || [ $retry_count -eq $max_retries ]; do
              echo "Retrying stack deployment... Attempt $((retry_count+1))"
              retry_count=$((retry_count+1))
              sleep 5
            done

            if [ $retry_count -eq $max_retries ]; then
              echo "Failed to deploy stack after $max_retries attempts."
              exit 1
            fi

            echo "Deployment completed successfully."
