name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger workflow only on push events to the main branch

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker if you're using containers
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub or another container registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-app:latest .
          docker push your-dockerhub-username/your-app:latest

      # Deploy to the server
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-address << EOF
          docker pull your-dockerhub-username/your-app:latest
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d --name your-container-name -p 80:80 your-dockerhub-username/your-app:latest
          EOF

